- purplship/purplship/core/utils/datetime.py
- Update typing for `DF.date` helper to explicitly define support for `Union[str, datetime]`
- Return None when `DF.date` is called with an empty string or blank string
- Return None when `DF.date` is called with None
> [enhancement] handle date helper input edge cases

- extensions/dhl_express/purplship/providers/dhl_express/tracking.py
- extensions/dhl_express/pyproject.toml
- poetry.lock
- purplship/purplship/core/utils/xml.py
- purplship/pyproject.toml
- pyproject.toml
- tests/dhl_express/tracking.py
DHL returns a different date `EstDlvyDate` than the format defined in the XML-pi toolkit.
Fix tracking response parsing by accessing directly the expected XML nodes
> [patch] DHL express tracking response parsing issue

- extensions/canadapost/purplship/providers/canadapost/rate.py
- extensions/canadapost/purplship/providers/canadapost/shipment/contract.py
- extensions/canadapost/purplship/providers/canadapost/shipment/non_contract.py
- extensions/canadapost/purplship/providers/canadapost/units.py
- extensions/canadapost/pyproject.toml
- purplship/purplship/core/utils/enum.py
- purplship/pyproject.toml
- tests/canadapost/rate.py
- implement EnumWrapper for simple enum data access
- use `.map` enum helper to simplify Canada post service parsing and allow fallback when unknown
> [patch] Improve Service reference parsing

- extensions/dhl_express/purplship/providers/dhl_express/rate.py
- extensions/dhl_express/purplship/providers/dhl_express/shipment.py
- extensions/dhl_express/purplship/providers/dhl_express/units.py
- extensions/dhl_express/pyproject.toml
- purplship/README.md
- Add `MeasurementOptions` to ensure DHL measurements never get rounded to 0
> [patch] DHL Express dimension rounded to 0 error

- insiders/server/documents/karrio/server/documents/generator.py
- insiders/server/documents/karrio/server/documents/views.py
- insiders/server/documents/setup.py
- Update document module carrier info parsing caused by previous changes that replace carrier_name by custom_carrier_name instead of generic.
> Patch Document module

- sdk/extensions/fedex/karrio/providers/fedex/shipment/create.py
- sdk/extensions/fedex/tests/fedex/shipment.py
I'm not sure if we should hide the whole `SpecialServicesRequested` when `signature_confirmation=false`, and what `signatureOptionType` we should use, I used ADULT for now.
also, we need to test if it shows the charge in `extra_charges`, for Canada post it doesn't show. 
P.S. I didn't test this code at all, (currently, I didn't figure out how to run it on my local machine)
> add FedEx signature request based on when option is selected

- sdk/extensions/ups/karrio/providers/ups/shipment/create.py
This fixes the following problems with UPS International Shipping customs invoice
- Soap XML prefix for childern of `InternationalForms` should be prefixed with `ifs` i.e. `<ifs:CurrencyCode>CAD</ifs:CurrencyCode>` not with `ship` prefix
- added default today date if now invoice date (because its required)
- item `Number` should be the quantity, not the index or items array
-  item code `OTH` is not valid for UPS, replaced for `PCS` (maybe user should have more control on it)
- `CommodityCode` they want the HS code
> Fix UPS International Shipping customs invoice

- docker/dashboard/.dockerignore
- docker/dashboard/Dockerfile
- modules/connectors/dhl_express/karrio/providers/dhl_express/rate.py
- modules/connectors/dhl_express/karrio/providers/dhl_express/shipment.py
- turbo.json
I am currently trying to set up karrio for our DHL shipments and our DHL contact reports that EU exports are not correctly declared as dutiable.
Since I'm a Ruby guy and don't know much about Python projects and I can't get the development environment to work on my machine, this is unfortunately just a code suggestion without tests. Sorry.
Some background:
* Exports from EU to the world (non-EU) are dutiable.
* Imports from world (non-EU) to EU are dutiable.
* Imports and exports within EU are not dutiable.
> Mark imports and exports from and to EU as dutiable (DHL Express)

- modules/connectors/fedex/karrio/providers/fedex/tracking.py
- modules/connectors/fedex/karrio/providers/fedex/units.py
- modules/connectors/ups/karrio/providers/ups/units.py
- modules/core/karrio/server/core/serializers.py
- modules/sdk/karrio/core/units.py
- (add) pending status to karrio SDK to handle event code when a package hasn't been picked up and can still be cancelled
> fix: non picked up shipment marked as in-transit

- modules/connectors/usps/karrio/providers/usps/shipment/create.py
- modules/connectors/usps/setup.py
- modules/connectors/usps/tests/usps/test_shipment.py
- modules/connectors/usps_international/karrio/providers/usps_international/shipment/first_class_mail.py
- modules/connectors/usps_international/karrio/providers/usps_international/shipment/global_express_guaranteed.py
- modules/connectors/usps_international/karrio/providers/usps_international/shipment/priority_express.py
- modules/connectors/usps_international/karrio/providers/usps_international/shipment/priority_mail.py
- modules/connectors/usps_international/setup.py
- modules/connectors/usps_international/tests/usps_international/test_shipment/test_first_class.py
- modules/connectors/usps_international/tests/usps_international/test_shipment/test_global_express_guaranteed.py
- modules/connectors/usps_international/tests/usps_international/test_shipment/test_priority_express.py
- modules/connectors/usps_international/tests/usps_international/test_shipment/test_priority_mail.py
- fix(#491): USPS label response conditional parsing when errors are returned and set defaults for secondary address lines
> [bug-fix] usps label response parsing

- modules/connectors/dhl_express/karrio/providers/dhl_express/shipment.py
- modules/connectors/dhl_express/tests/dhl_express/test_shipment.py
Our contact person at DHL pointed out to us that the CommodityCode must be the HS Code. The same applies to the ImportCommodityCode. The DHL API documentation on this is a bit poor.
> DHL Express: Use HS code for customs declaration

- modules/graph/karrio/server/graph/forms.py
email reset is currently falling back to `DEFAULT_FROM_EMAIL` which fallback to `webmaster@localhost`
I would also strongly suggest not to show on the front-end the SMTP error for security
> fix password reset to use EMAIL_FROM_ADDRESS as sender

- modules/connectors/fedex/karrio/providers/fedex/error.py
We have previously chosen to disregard "note" alerts from fedex in fedex_ws due to their extensive number. As such, they will be ignored for the time being.
**Reference to our approach in fedex_ws:** https://github.com/karrioapi/karrio/blob/4d2a07b6c3c1a267783e0275260f523882b149ef/modules/connectors/fedex_ws/karrio/providers/fedex_ws/error.py#L20-L20
The handling of note messages as a distinct error type can be revised and better integrated into our codebase in future updates
> Disable "note" alert types as previously done in fedex_ws

- modules/connectors/fedex/karrio/providers/fedex/rate.py
- modules/connectors/fedex/karrio/providers/fedex/shipment/create.py
For some reason FedEx in quebec is considering "QC" province as wrong and only "PQ" is the correct one, and is returning this message all the time
```
{
"message": "The origin state/province code has been changed.",
"code": "ORIGIN.STATEORPROVINCECODE.CHANGED",
"details": {},
"carrier_name": "fedex",
"carrier_id": "fedex_test"
}
```
so the commit is doing it by hardcoding it, but I'm open to replacing this as a method, but I wasn't sure where to place it in utils.py?
> Standardize "QC" to "PQ" for stateOrProvinceCode in FedEx

- modules/connectors/eshipper/karrio/providers/eshipper/shipment/create.py
- modules/connectors/eshipper/karrio/providers/eshipper/utils.py
The URL property has been updated to return the correct URL based on the flag. This ensures that the production and test environments are targeted correctly.
Eshipper returns the label type as lowercase, but the system uses uppercase. Therefore, a conversion has been added.
> Fix eShipper server URL for production mode and label problem

- modules/connectors/fedex/karrio/providers/fedex/shipment/create.py
A bug was creating multiple of the same package if packages were more then 1
in the future we can have a function that conslidate same dimantine packages to only show one time in the api and ask for x times the same pacakge
> Fix FedEx multi shipment creating multiple of packages

- modules/connectors/eshipper/karrio/providers/eshipper/rate.py
- modules/connectors/eshipper/karrio/providers/eshipper/shipment/create.py
Ensures that shipping date isn't set to a past date, correcting to the current date if necessary. Eshipper Skip Carrier was complaining that date is before now, because they don't like when its pest time
> Fix: set shipping date to now if it is in the past

- modules/connectors/eshipper/karrio/providers/eshipper/error.py
- modules/connectors/eshipper/karrio/providers/eshipper/shipment/cancel.py
Eshipper is good news! 😢 
As per the docs, we can use either `orderId` or `trackingId` but `orderId` is better in case where we have multiple packages.
in fact, till now we wrongly sent the `orderId` value as the `trackingId` in the cancel request.
Testing with the API, it turns out that the cancel request is not responding to the documented errors, it returns a status code 200 and just has an error in the body
In case when I tried to cancel an order that was already canceled it return the error in this format
```json
{
"order": [
{
"message": "Error: The Shipping Order is already cancelled",
"orderId": "8000000011008",
"trackingId": null
}
]
}
```
or in case i tested with a old traking order
```json
{
"order": [
{
"message": "Error: Purolator orders cannot be cancelled after 24 hours", …
```
> Eshipper fix cancel shipment request, and adding special error handling 

- modules/connectors/ups/karrio/providers/ups/shipment/create.py
* UPS: Add additional package level ReferenceNumber to UPS API request
* UPS: Remove optional keys from shipment level ReferenceNumber field which were incorrect or hardcoded anyway
> Fixes #667: UPS ReferenceNumber changes

- docker/api/Dockerfile
- docker/docker-compose.yml
Hi guys, 
Thank you so much for the hardwork, it's great apps and smooth apps. I also build something like this but for my private client and using several local shipment  service in indonesia.
Just my two cents,  when i started to test karrio i realize that API container startups is sometimes really slow. So i came up with this idea to add healthcheck in docker compose so users will understand why their frontend returning such error because the API not finished startup yet.
But let me know if such discussion already made or maybe any specific concern arose before that end up to not add this kind of functionality to docker compose due that concern
Thank you!
Best regards,
Panji
> Proposal to add health check due to api startup that somehow can be slow

- modules/connectors/canadapost/karrio/providers/canadapost/shipment/create.py
- modules/connectors/canadapost/tests/canadapost/test_shipment.py
This change corrects the assignment of the shipment identifier to use `info.shipment_id` instead of `info.tracking_pin`. This ensures that the shipment identifier is correctly set, allowing to cancel or refund of shipments.
> Fix shipment identifier assignment in create shipment

- apps/www/docs/index.mdx
- In the `cardgrid` the management tile had a typo. Managment -> Management
> docs: In the cardgrid the management tile had a typo

- modules/sdk/karrio/core/utils/datetime.py
This small PR resolves the `datetime` library warnings:
```python
DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
```
> fix: resolve warnings of datetime library

- packages/core/modules/Orders/draft_order.tsx
- packages/ui/components/commodity-edit-dialog.tsx
This hotfix resolves issues with the commodity form’s enhanced metadata editor not being reflected due to conflicts with older code. It ensures the correct editor is now in place and working as intended.
- Enhanced metadata editor added to the commodity form  
- Removed unnecessary line-item unlinking mechanisms  
- Added a warning for mixed currencies when multiple items with different currencies are included in the same order (using the existing warning card at the top)
> hotfix/commodity form - metadata editor

- modules/sdk/karrio/core/utils/helpers.py
Shipment level reference numbers are only valid for **non** US/PR shipments.
Package level reference numbers are only valid **for** US/PR shipments.
Very confusing, but per the UPS docs I believe this is the right way to do it, otherwise its impossible to add reference numbers for UPS US/PR shipments.
> UPS: Package number references allowed for US and PR shipments

- packages/ui/components/order-menu.tsx
Fixed broken navigation in `OrderMenu` when `basePath` was undefined in non-test environments, causing invalid URLs like `http://orders/...`.  
- Replaced `router.push(basePath + "...")` with `router.push(p`...`)` for reliable path construction.  
- Removed dependency on `useAppMode()` and `basePath`.  
- Ensured consistent navigation for **View Order**, **Create Label**, and **Edit Order** across all environments.  
Verified navigation works in both test mode (on) and normal mode (off).
> fix: order-menu navigation
