karrioapi/karrio

- purplship/mappers/caps/caps_client.py
- purplship/mappers/dhl/dhl_client.py
- purplship/mappers/fedex/fedex_client.py
- purplship/mappers/fedex/fedex_mapper/partials/rate.py
- purplship/mappers/fedex/fedex_mapper/partials/shipment.py
- purplship/mappers/fedex/fedex_mapper/partials/track.py
- purplship/mappers/ups/ups_client.py
- purplship/mappers/ups/ups_mapper/partials/rate.py
- tests/dhl/fixture.py
- tests/fedex/fixture.py
- tests/fedex/quote.py
- tests/fedex/shipment.py
- tests/ups/fixture.py
- tests/ups/quote.py
> Update shipping carriers client settings

- README.md
- cli.py
- extensions/canadapost/setup.py
- extensions/dhl/setup.py
- extensions/fedex/setup.py
- extensions/freight/setup.py
- extensions/package/setup.py
- extensions/purolator/setup.py
- extensions/ups/setup.py
- extensions/usps/setup.py
- purplship/core/models.py
- script.sh
- setup.py
- Update version to 2020.6.0
- Write purplship SDK documentation.
> update release version and draft README extended documentation

- extensions/canadapost/purplship/carriers/canadapost/rating.py
- extensions/canadapost/purplship/carriers/canadapost/shipment/contract_shipment.py
- extensions/canadapost/purplship/carriers/canadapost/shipment/non_contract_shipment.py
- extensions/dhl/purplship/carriers/dhl/dct_quote.py
- extensions/dhl/purplship/carriers/dhl/ship_val.py
- extensions/fedex/purplship/carriers/fedex/package/rate.py
- extensions/fedex/purplship/carriers/fedex/package/ship_service.py
- extensions/package/purplship/package/interface.py
- extensions/purolator/purplship/carriers/purolator/package/estimate_service.py
- extensions/purolator/purplship/carriers/purolator/package/shipping_service/create_shipping.py
- extensions/ups/purplship/carriers/ups/package/rate.py
- extensions/ups/purplship/carriers/ups/package/shipment.py
- purplship/core/errors.py
- tests/canadapost/rate.py
> Introduce FieldError

- extensions/canadapost/purplship/carriers/canadapost/rating.py
- extensions/canadapost/purplship/carriers/canadapost/shipment/contract_shipment.py
- extensions/canadapost/purplship/carriers/canadapost/shipment/non_contract_shipment.py
- extensions/dhl/purplship/carriers/dhl/dct_quote.py
- extensions/dhl/purplship/carriers/dhl/ship_val.py
- extensions/fedex/purplship/carriers/fedex/package/rate.py
- extensions/fedex/purplship/carriers/fedex/package/ship_service.py
- extensions/package/purplship/package/interface.py
- extensions/purolator/purplship/carriers/purolator/package/estimate_service.py
- extensions/purolator/purplship/carriers/purolator/package/shipping_service/create_shipping.py
- extensions/ups/purplship/carriers/ups/package/rate.py
- extensions/ups/purplship/carriers/ups/package/shipment.py
- purplship/core/errors.py
- tests/canadapost/rate.py
> Release 2020.7.0

- README.md
- Update versions and model changes in README
> update doc for release

- purplship/core/utils/helpers.py
- setup.py
> Devfix request data logging

- README.md
- purplship/core/models.py
> add meta field for carrier specific additional metadata

- .github/workflows/pythonpackage.yml
- extensions/canadapost/purplship/providers/canadapost/rate.py
- extensions/canadapost/purplship/providers/canadapost/shipment/contract.py
- extensions/canadapost/purplship/providers/canadapost/shipment/non_contract.py
- extensions/canadapost/purplship/providers/canadapost/units.py
- extensions/canadapost/setup.py
- extensions/ups/purplship/providers/ups/package/shipment/create.py
- extensions/ups/setup.py
- purplship/core/utils/helpers.py
- requirements.dev.txt
- script.sh
- setup.py
- tests/canadapost/rate.py
- Fix Canada postal code space trimming
- Fix canadapost rate options value computation
> [patch] purplship SDK 2020.11

- extensions/boxknight/pyproject.toml
- extensions/boxknight/setup.py
- extensions/canadapost/pyproject.toml
- extensions/canadapost/setup.py
- extensions/canpar/pyproject.toml
- extensions/canpar/setup.py
- extensions/dhl_express/pyproject.toml
- extensions/dhl_express/setup.py
- extensions/dicom/pyproject.toml
- extensions/dicom/setup.py
- extensions/fedex/pyproject.toml
- extensions/fedex/setup.py
- extensions/fedex_express/pyproject.toml
- extensions/fedex_express/setup.py
- extensions/purolator_courier/pyproject.toml
- extensions/purolator_courier/setup.py
- extensions/ups/pyproject.toml
- extensions/ups/setup.py
- extensions/ups_package/pyproject.toml
- extensions/ups_package/setup.py
- extensions/usps/pyproject.toml
- extensions/usps/setup.py
- purplship/README.md
- purplship/pyproject.toml
- purplship/setup.py
- pyproject.toml
- script.sh
- Add `setup.py` so that packages can be installed with pip and git
- Adjust `pyproject.toml` to coexist with `setup.py`
> [dev:ex] add setup.py to make packages installable with pip and git

- extensions/purolator_courier/purplship/providers/purolator_courier/rate.py
- extensions/purolator_courier/purplship/providers/purolator_courier/shipment/create.py
- extensions/purolator_courier/purplship/providers/purolator_courier/units.py
- extensions/purolator_courier/pyproject.toml
- tests/purolator_courier/rate.py
- tests/purolator_courier/shipment.py
- fix: show alternate service when none is specified
> [patch] purolator-courier alternate rates services

- extensions/canadapost/purplship/providers/canadapost/pickup/create.py
- extensions/canadapost/purplship/providers/canadapost/rate.py
- extensions/canadapost/purplship/providers/canadapost/shipment/contract.py
- extensions/canadapost/purplship/providers/canadapost/shipment/non_contract.py
- extensions/canadapost/pyproject.toml
- tests/canadapost/rate.py
- tests/canadapost/shipment.py
Canadapost request validator expects Canadian postal code without space in between
> [patch] format postal code for canadapost requests

- .github/FUNDING.yml
- extensions/canadapost/purplship/providers/canadapost/shipment/contract.py
- extensions/canadapost/pyproject.toml
- extensions/dhl_universal/purplship/providers/dhl_universal/tracking.py
- extensions/dhl_universal/pyproject.toml
- Fix canadapost international shipment customs and duty mapping
- Fix DHL universal tracking when delivered status is not returned
> Minor bug fixes

- server/modules/core/purplship/server/core/serializers.py
- server/schemas/openapi.json
- server/schemas/swagger.json
Fix Tracker status using Shipment status enum instead of Tracking status enum
> [patch] fix tracker status enum

- extensions/fedex/purplship/mappers/fedex/settings.py
- extensions/fedex/purplship/providers/fedex/utils.py
- Make FedEx extension user_key setting optional
> [patch] FedEx User Key setting

- LICENSE
- README.md
- server/modules/events/purplship/server/events/tasks/tracking.py
- server/modules/events/purplship/server/events/tests/test_tracking_tasks.py
- fix renamed dict -> to_dict usage in background tracking
> [patch] fix background tracker processing error

- insiders/server/orders/purplship/server/graph/extension/orders/types.py
- insiders/server/orders/setup.py
- server/modules/core/purplship/server/core/gateway.py
- server/modules/core/setup.py
- server/schemas/graphql.json
- Add filter for orders by uuids
- Fix bug with carrier filter returning multiple values
> [hot-fix] Purplship 2022.2

- insiders/server/tenants/setup.py
- sdk/extensions/dhl_express/karrio/providers/dhl_express/rate.py
- sdk/extensions/dhl_express/setup.py
- (fix) invalid import of `CountryCurrency`
> [patch]dhl 2022.8

- sdk/vendors/eshipper/karrio/providers/eshipper/shipping.py
- sdk/vendors/eshipper/setup.py
- sdk/vendors/eshipper/tests/eshipper/shipment.py
- sdk/vendors/freightcom/karrio/providers/freightcom/shipping.py
- sdk/vendors/freightcom/setup.py
- (fix) hs_code mapping for `freightcom` and `eshipper`
> [patch] 2022.8.7.02

- bin/deploy-hobby
- bin/upgrade-hobby
- docker/docker-compose.yml
- requirements.light.txt
- requirements.txt
- sdk/extensions/fedex/karrio/providers/fedex/tracking.py
- sdk/extensions/fedex/setup.py
- sdk/extensions/ups/karrio/providers/ups/tracking.py
- sdk/extensions/ups/setup.py
- (fix) tracking info parsing for UPS and FedEx responses
> [hot-fix] 2023.3.2.01

- server/modules/core/karrio/server/core/filters.py
- server/modules/graph/karrio/server/graph/schemas/base/inputs.py
this PR tries to add a filter for the `remote_addr` field in the logs
Dashboard PR: https://github.com/karrioapi/karrio-dashboard/pull/260
> Add remote_addr filter

- bin/deploy-hobby
- bin/upgrade-hobby
- docker/docker-compose.yml
- requirements.light.txt
- requirements.txt
- sdk/extensions/canadapost/karrio/providers/canadapost/rate.py
- sdk/extensions/canadapost/karrio/providers/canadapost/shipment/contract.py
- sdk/extensions/canadapost/karrio/providers/canadapost/shipment/non_contract.py
- sdk/extensions/canadapost/setup.py
- (fix) Canada post empty options XML node when options are specified but falsy
> [hot-fix] 2023.4.6.01

- requirements.sdk.dev.txt
- requirements.server.dev.txt
- (use) SDK extensions dev install for server local development
- (add) missing schemas dev installs for SDK dev requirements
> [dev-ex] development setup

- modules/connectors/dhl_express/karrio/providers/dhl_express/shipment.py
- modules/connectors/dhl_express/karrio/providers/dhl_express/units.py
- modules/connectors/dhl_express/tests/dhl_express/test_shipment.py
Sorry for bringing up the paperless_trade topic again, but it's still not working. I've sat down again to try to solve the problem. The code is from Copilot and I don't know if it works correctly / is correct. As I said: Python is not my world at all.
> paperless_trade again.

- apps/dashboard/src/context/main.ts
- apps/dashboard/src/pages/api/auth/[...nextauth].ts
- modules/connectors/fedex/karrio/providers/fedex/tracking.py
- packages/hooks/karrio.tsx
- packages/hooks/organization.tsx
- packages/ui/components/organization-dropdown.tsx
- (fix) dashboard org switcher inconsistency
> fix: org switching issues

- apps/api/karrio/server/settings/apm.py
- apps/api/setup.py
- apps/dashboard/next.config.js
- apps/dashboard/package.json
- apps/dashboard/src/pages/_app.tsx
- apps/www/docusaurus.config.js
- apps/www/package.json
- package-lock.json
- packages/hooks/posthog.tsx
- requirements.txt
- source.requirements.txt
- feat: Add support for Posthog  on the API, dashboard and docs
> feat: PostHog support

- apps/dashboard/src/modules/Settings/addresses.tsx
- apps/dashboard/src/modules/Settings/parcels.tsx
- apps/dashboard/src/modules/Settings/templates.tsx
- packages/ui/admin/staff-management.tsx
- packages/ui/forms/organization-management.tsx
- fix: table pagination responsiveness
> [minor-patch] UI list responsiveness

- apps/dashboard/src/modules/Connections/rate-sheets.tsx
- apps/dashboard/src/modules/Connections/system.tsx
- apps/dashboard/src/modules/Orders/create_shipment.tsx
- apps/dashboard/src/modules/Orders/index.tsx
- apps/dashboard/src/modules/Shipments/create_label.tsx
- apps/dashboard/src/modules/Shipments/index.tsx
- apps/dashboard/src/modules/Shipments/shipment.tsx
- apps/dashboard/src/pages/_sites/[site]/connections/rate-sheets.tsx
- apps/dashboard/src/pages/_sites/[site]/connections/system.tsx
- apps/dashboard/src/pages/_sites/[site]/test/connections/rate-sheets.tsx
- apps/dashboard/src/pages/_sites/[site]/test/connections/system.tsx
- apps/dashboard/src/pages/api/images/[name].ts
- apps/dashboard/src/pages/connections/rate-sheets.tsx
- apps/dashboard/src/pages/connections/system.tsx
- apps/dashboard/src/pages/test/connections/rate-sheets.tsx
- apps/dashboard/src/pages/test/connections/system.tsx
- apps/dashboard/src/styles/dashboard.scss
- modules/graph/karrio/server/graph/schemas/base/mutations.py
- modules/sdk/karrio/universal/mappers/rating_proxy.py
- packages/ui/components/carrier-badge.tsx
- packages/ui/components/carrier-image.tsx
- packages/ui/components/rate-description.tsx
- packages/ui/forms/rate-sheet-list.tsx
- packages/ui/forms/user-carrier-list.tsx
- packages/ui/modals/connect-provider-modal.tsx
- packages/ui/modals/rate-sheet-editor.tsx
- chore: fix orders and shipments list styling
- feat: Improve generic carrier brand color rendering
- feat: Make allied express service_type and account_service_type config plain text input fields
> [patch] 2024.3 rc

- .env
- apps/api/karrio/server/settings/cache.py
- apps/api/karrio/server/settings/workers.py
- docker/.env
- docker/docker-compose.yml
> [feat] Add env variables for password protected Redis connection

- apps/www/docs/carriers/sdk/extension.mdx
- bin/update-version
- modules/core/karrio/server/core/serializers.py
- modules/core/karrio/server/providers/models/carrier.py
- modules/core/setup.py
- modules/documents/karrio/server/documents/generator.py
- modules/documents/karrio/server/documents/models.py
- modules/documents/karrio/server/documents/serializers/__init__.py
- modules/documents/karrio/server/documents/serializers/base.py
- modules/documents/karrio/server/documents/serializers/documents.py
- modules/documents/karrio/server/documents/urls.py
- modules/documents/karrio/server/documents/views/printers.py
- modules/documents/karrio/server/documents/views/templates.py
- modules/documents/karrio/server/graph/schemas/documents/inputs.py
- modules/documents/setup.py
- modules/manager/karrio/server/manager/models.py
- modules/manager/karrio/server/manager/serializers/shipment.py
- modules/manager/karrio/server/manager/views/documents.py
- modules/manager/setup.py
- schemas/graphql.json
- schemas/openapi.yml
- feat: Enhance Documents REST API with support for template management CRUD operations and generic document generator API in addition to Trade API upload API
- chore: Apply minimal query optimization
- chore: Prevent backup file creation from sed command
> [feat] Advanced Document api

- apps/www/docs/product/connections.mdx
> chore: Fix typo in connections.mdx file

- modules/connectors/fedex/karrio/mappers/fedex/proxy.py
- modules/connectors/fedex/karrio/providers/fedex/error.py
- modules/connectors/fedex/karrio/providers/fedex/rate.py
- modules/connectors/fedex/karrio/providers/fedex/shipment/create.py
- modules/connectors/fedex/karrio/providers/fedex/utils.py
- modules/connectors/fedex/karrio/schemas/fedex/rating_response.py
Fedex with multi packages was broken
Fedex Taxes did not show
> Fix Fedex multiship

- modules/connectors/eshipper/karrio/providers/eshipper/rate.py
- modules/connectors/eshipper/karrio/providers/eshipper/shipment/create.py
Refactored the package dimension and weight handling to use the `math.ceil` function for rounding values. Adjusted the unit assignments to use the package's own units directly and included conditional logic for weight unit conversions between Metric and Imperial systems.
> Update package dimension handling and unit conversions

- CHANGELOG.md
- apps/www/docs/reference/api/add-carrier-connection.api.mdx
- apps/www/docs/reference/api/list-carrier-connections.api.mdx
- apps/www/docs/reference/api/remove-carrier-connection.api.mdx
- apps/www/docs/reference/api/retrieve-carrier-connection.api.mdx
- apps/www/docs/reference/api/update-carrier-connection.api.mdx
- apps/www/openapi.yml
- modules/connectors/dhl_express/karrio/providers/dhl_express/shipment.py
- modules/connectors/dhl_express/tests/dhl_express/test_shipment.py
- feat: switch export line item description to description (`dhl express`) @DarkSwoop
> [patch] 2024.9.14

- modules/connectors/ups/karrio/providers/ups/shipment/create.py
Sorry ,forgot change it in last pr ,last pr just fix the rate api
> fix ups signature issue in shipment api 

- .github/workflows/platform-tests.yml
- apps/dashboard/.env.sample
- ee/apps/platform/.env.sample
> [chore] Debug insiders and platform builds setup 

- apps/www/docs/product/resources/development.mdx
- ee/packages/console/components/pricing-section.tsx
- requirements.dev.txt
This dependency was creating conflicts during the migration process and is not needed.
> "Remove pycairo dependency"

- modules/connectors/dhl_poland/tests/dhl_poland/test_shipment.py
- modules/sdk/karrio/core/units.py
There was a bug with the NIP number showing the EORI.
> fix incorrect nip number

- apps/www/docusaurus.config.js
- apps/www/src/css/custom.css
- apps/www/src/theme/Footer/Copyright/index.js
- apps/www/src/theme/Footer/LinkItem/index.js
- apps/www/src/theme/Footer/Links/index.js
- apps/www/src/theme/Footer/Logo/index.js
- apps/www/src/theme/Footer/index.js
- apps/www/src/theme/Footer/styles.css
- apps/www/static/img/logo-inverted.svg
- ee/packages/console/components/book-demo-button.tsx
- ee/packages/console/components/pricing-section.tsx
- ee/packages/console/layouts/website-layout.tsx
- ee/packages/console/modules/website/index.tsx
- ee/packages/console/modules/website/use-cases/enterprise-solutions/index.tsx
- package-lock.json
- package.json
Updated all external links to point to their correct destinations (Carriers, Product, Platform, Blog)
Maintained the responsive four-column layout with logo, tagline, and copyright information.
- chore: added functionality to footer of karrio.docs and https://platform.karrio.io/
- chore: updated number of labels to 120,000
> chore: add functionality to foooter of site

- .gitignore
Plugins
- chore: set up plugin folder
- chore: set up examples folder
> chore: setup plugin folder

- modules/connectors/fedex/karrio/providers/fedex/error.py
small fix for fedex cancellations
> fix for fedex shipment cancellation

- docker/docker-compose.yml
- packages/admin/package.json
- hotfix: dashboard admin build
> [chore] admin dashboard build
